package com.lnight.moviecomposeapp.common

object Constants {
    const val API_KEY = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYzdiODdmMWRlMWU0MGJmZDU2NDFkNjU3MGU3NjQxOCIsInN1YiI6IjYxYTdiMjBiMTgwZGVhMDA0NTVjODlhYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-xMm-S51BEWy1sDv0Yg-maUVJpz-03AwfePfnbOitJw"
}